variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build

tysocks_linux32:
  stage: build
  tags:
    - kirito
    - archlinux
    - i686
  script:
    - mkdir build-linux32
    - cd build-linux32
    - cmake .. -DENABLE_SEC=1 -DBUILD_STATIC=1
    - make -j2
  artifacts:
    paths:
      - build-linux32/tysocks_*
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"

tysocks_linux64:
  stage: build
  tags:
    - kirito
    - archlinux
    - x86_64
  script:
    - mkdir build-linux64
    - cd build-linux64
    - cmake .. -DENABLE_SEC=1 -DBUILD_STATIC=1
    - make -j2
  artifacts:
    paths:
      - build-linux64/tysocks_*
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"

tysocks_win32:
  stage: build
  tags:
    - mingw
    - i686
  variables:
    TARGET: "i686-w64-mingw32"
  script:
    - /usr/local/bin/mingwclean
    - mkdir build-win32
    - cd build-win32
    - ${TARGET}-cmake .. -DENABLE_SEC=1 -DBUILD_STATIC=1
    - make -j2
  artifacts:
    paths:
      - build-win32/tysocks_*
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"

tysocks_win64:
  stage: build
  tags:
    - mingw
    - x86_64
  variables:
    TARGET: "x86_64-w64-mingw32"
  script:
    - /usr/local/bin/mingwclean
    - mkdir build-win64
    - cd build-win64
    - ${TARGET}-cmake .. -DENABLE_SEC=1 -DBUILD_STATIC=1
    - make -j2
  artifacts:
    paths:
      - build-win64/tysocks_*
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"

tysocks_armv5tel:
  stage: build
  tags:
    - armv5tel
  variables:
    TARGET: "armv5tel-unknown-linux-gnueabi"
  script:
  - mkdir build-armv5tel
  - cd build-armv5tel
  - ${TARGET}-cmake .. -DENABLE_SEC=1 -DBUILD_STATIC=1
  - make -j2
  artifacts:
    paths:
      - build-armv5tel/tysocks_*
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"

tysocks_armv6h:
  stage: build
  tags:
    - armv6h
  variables:
    TARGET: "armv6l-unknown-linux-gnueabihf"
  script:
  - mkdir build-armv6h
  - cd build-armv6h
  - ${TARGET}-cmake .. -DENABLE_SEC=1 -DBUILD_STATIC=1
  - make -j2
  artifacts:
    paths:
      - build-armv6h/tysocks_*
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"

tysocks_armv7h:
  stage: build
  tags:
    - armv7h
  variables:
    TARGET: "armv7l-unknown-linux-gnueabihf"
  script:
  - mkdir build-armv7h
  - cd build-armv7h
  - ${TARGET}-cmake .. -DENABLE_SEC=1 -DBUILD_STATIC=1
  - make -j2
  artifacts:
    paths:
      - build-armv7h/tysocks_*
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"

tysocks_darwin64:
  stage: build
  tags:
    - darwin64
  variables:
    TARGET: "x86_64-apple-darwin15"
  script:
  - mkdir build-darwin64
  - cd build-darwin64
  - ${TARGET}-cmake .. -DENABLE_SEC=1 -DBUILD_STATIC=1
  - make -j2
  artifacts:
    paths:
      - build-darwin64/tysocks_*
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
